name: English Master Otomatik Derleme

on:
  push:
    branches: [ "main" ]

jobs:
  apk_olustur:
    runs-on: ubuntu-latest
    
    steps:
      - name: Kodu Buluttan Cek
        uses: actions/checkout@v3

      - name: Java (Android) Altyapisini Kur
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Flutter SDK Kurulumu
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Paketleri ve Eklentileri Indir
        run: flutter pub get

      - name: Android APK Derle
        run: flutter build apk --release
      
      - name: APK Dosyasini Cantaya Koy (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: english-master-apk
          path: build/app/outputs/flutter-apk/app-release.apk
 
      - name: Firebase App Distribution'a Yukle
        uses: w9jds/firebase-action@master
        with:
          args: appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk --app ${{ secrets.FIREBASE_APP_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
